module.exports = {
  apps: [
    {
      name: "simulate-plane-test",
      script: "src/index.js",
      exec_mode: "cluster",
      instances: "1",
      watch: true,
      env: {
        NODE_ENV: "test",
        SENDER_PORT: 65000,
        SENDER_HOST: "127.0.0.1",
        RECEIVER_PORT: 65001,
        RECEIVER_HOST: "127.0.0.1",
        PORT: 1000,
        WS_PORT: 1001,
        JWT_SECRET: "your_jwt_secret_test",
      },
    },
    {
      name: "simulate-plane-dev",
      script: "src/index.js",
      exec_mode: "cluster",
      instances: "1",
      watch: true,
      env: {
        NODE_ENV: "development",
        SENDER_PORT: 65000,
        SENDER_HOST: "127.0.0.1",
        RECEIVER_PORT: 65001,
        RECEIVER_HOST: "127.0.0.1",
        PORT: 3000,
        WS_PORT: 3001,
        JWT_SECRET: "your_jwt_secret_dev",
      },
    },
    {
      name: "simulate-plane-prod",
      script: "src/index.js",
      exec_mode: "cluster",
      instances: 1,
      watch: true,
      env: {
        NODE_ENV: "production",
        SENDER_PORT: 65000,
        SENDER_HOST: "127.0.0.1",
        RECEIVER_PORT: 65001,
        RECEIVER_HOST: "127.0.0.1",
        PORT: 4000,
        WS_PORT: 4001,
        JWT_SECRET: "your_jwt_secret_prod",
      },
    },
  ],
};
